### ISSUE TITLE
建议按照中文 markdown 格式规范编写

### ISSUE THREAD

**Issue by hustcc** [geekcompany/ResumeSample#23]
建议按照这个：[中文技术文档的写作规范](https://github.com/ruanyf/document-style-guide)。

然后可以使用 [lint-md](https://github.com/hustcc/lint-md) 进行格式校验，然后开启 travis-ci 进行自动检查。

如果接受，我可以帮忙提 pr！

**Comment by easychen** [comment]
我们用自己的md规范。
