### ISSUE TITLE
将项目经历写在工作经历里面?

### ISSUE THREAD

**Issue by anson0** [geekcompany/ResumeSample#25]
你好,谢谢你的文章,看后感觉受启发.
在文章中项目经历写在工作经历里面,这个与一般的简历格式不大一样啊,一般简历是工作经历里面简述各个工作的工作内容.然后有专门的项目经历栏目,用来填写项目经历,各大招聘网站也都是有专门的项目经历的栏目的,请问你的建议是将项目经历写在工作经历里面吗?项目背景是不是也要包含呢?

**Comment by easychen** [comment]
因为重复了，看着烦，而且容易导致一页打印不下来，所以就合起来写了。怎么写都行，你愿意按「一般简历」格式去写就照那个写呗。
